# OpenAI Gym 사용하기

In [2]:
import gym

env = gym.make('CartPole-v0')
for i in range(10):
    env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        print(obs)
    env.close()

[-0.01902652  0.14844181 -0.02227441 -0.30996156]
[-0.01605768 -0.04635582 -0.02847364 -0.02438574]
[-0.0169848  -0.2410581  -0.02896136  0.25917919]
[-0.02180596 -0.43575489 -0.02377777  0.54258845]
[-0.03052106 -0.24030697 -0.012926    0.24250944]
[-0.0353272  -0.04500279 -0.00807582 -0.05422249]
[-0.03622725  0.15023402 -0.00916027 -0.34944242]
[-0.03322257  0.34548504 -0.01614911 -0.64499976]
[-0.02631287  0.54082827 -0.02904911 -0.94272403]
[-0.01549631  0.34610953 -0.04790359 -0.65930838]
[-0.00857411  0.15168585 -0.06108976 -0.38208568]
[-0.0055404  -0.04251789 -0.06873147 -0.10927268]
[-0.00639076 -0.23659106 -0.07091692  0.16095859]
[-0.01112258 -0.43062987 -0.06769775  0.43045311]
[-0.01973517 -0.62473114 -0.05908869  0.70105015]
[-0.0322298  -0.42884204 -0.04506769  0.39036735]
[-0.04080664 -0.2331104  -0.03726034  0.08382258]
[-0.04546885 -0.03747469 -0.03558389 -0.2203793 ]
[-0.04621834  0.15813735 -0.03999147 -0.52407108]
[-0.04305559 -0.03639963 -0.0504729  -0.24425328]


C:\ProgramData\Anaconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


[ 0.07684689  0.77730407 -0.43556724 -2.34493459]
[ 0.09239297  0.58787222 -0.48246593 -2.21136332]
[ 0.10415041  0.3993998  -0.5266932  -2.09733061]
[ 0.11213841  0.21182088 -0.56863981 -2.00188212]
[ 0.11637483  0.02506342 -0.60867745 -1.92414478]
[ 0.1168761  -0.16094659 -0.64716035 -1.86334367]
[ 0.11365716  0.0338501  -0.68442722 -2.27371608]
[ 0.11433417 -0.15199999 -0.72990154 -2.24360175]
[ 0.11129417  0.0407047  -0.77477358 -2.65505673]
[ 0.11210826 -0.14539537 -0.82787471 -2.66125076]
[ 0.10920035  0.04425544 -0.88109973 -3.07021223]
[ 0.11008546 -0.14277675 -0.94250397 -3.11850157]
[ 0.10722993 -0.32979807 -1.00487401 -3.19147047]
[ 0.10063397 -0.51705452 -1.06870341 -3.28902539]
[ 0.09029287 -0.33534977 -1.13448392 -3.67791027]
[ 0.08358588 -0.52551031 -1.20804213 -3.8238244 ]
[ 0.07307567 -0.71696609 -1.28451862 -3.9967845 ]
[ 0.05873635 -0.54452132 -1.36445431 -4.35186249]
[ 0.04784593 -0.74107394 -1.45149156 -4.57922102]
[ 0.03302445 -0.57644495 -1.54307598 -4.90052285]


[ 0.01524691  0.224199   -0.03186949 -0.3256857 ]
[ 0.01973089  0.02954496 -0.03838321 -0.04322095]
[ 0.02032179  0.22519569 -0.03924762 -0.34776278]
[ 0.0248257   0.03065332 -0.04620288 -0.06770978]
[ 0.02543877 -0.16377682 -0.04755708  0.21004538]
[ 0.02216323  0.03199172 -0.04335617 -0.09725194]
[ 0.02280307  0.22770739 -0.04530121 -0.40329227]
[ 0.02735722  0.42344158 -0.05336705 -0.70990634]
[ 0.03582605  0.22909777 -0.06756518 -0.43448812]
[ 0.040408    0.03499416 -0.07625494 -0.16384608]
[ 0.04110789 -0.15895805 -0.07953186  0.10383957]
[ 0.03792873  0.03720826 -0.07745507 -0.21283751]
[ 0.03867289 -0.15672577 -0.08171182  0.05444234]
[ 0.03553838 -0.3505868  -0.08062297  0.32026709]
[ 0.02852664 -0.54447354 -0.07421763  0.58647503]
[ 0.01763717 -0.34839487 -0.06248813  0.27136674]
[ 0.01066927 -0.15243948 -0.0570608  -0.04035222]
[ 0.00762048 -0.34669873 -0.05786784  0.23379564]
[ 0.00068651 -0.54094817 -0.05319193  0.50767842]
[-0.01013246 -0.34511868 -0.04303836  0.19871859]


[ 0.44036607  1.12638079 -5.33123892 -2.59643434]
[ 0.46289368  0.93893941 -5.3831676  -2.193856  ]
[ 0.48167247  0.74903889 -5.42704472 -1.78649253]
[ 0.49665325  0.55717879 -5.46277457 -1.37582335]
[ 0.50779682  0.73936656 -5.49029104 -1.34714057]
[ 0.52258415  0.54553373 -5.51723385 -0.93365481]
[ 0.53349483  0.72767532 -5.53590695 -0.92675771]
[ 0.54804834  0.53256738 -5.5544421  -0.51226251]
[ 0.55869968  0.71482116 -5.56468735 -0.52042358]
[ 0.57299611  0.51897575 -5.57509582 -0.10574944]
[ 0.58337562  0.32284614 -5.57721081  0.30893516]
[ 0.58983254  0.12674376 -5.57103211  0.72352011]
[ 0.59236742  0.30939845 -5.55656171  0.70824636]
[ 0.59855539  0.11379725 -5.54239678  1.1228601 ]
[ 0.60083133 -0.08114037 -5.51993958  1.5370493 ]
[ 0.59920853 -0.27505257 -5.48919859  1.95046312]
[ 0.59370747 -0.09129184 -5.45018933  1.96690375]
[ 0.59188164  0.09213603 -5.41085126  1.99937163]
[ 0.59372436  0.27532081 -5.37086382  2.04783327]
[ 0.59923077  0.45835954 -5.32990716  2.11236045]


[ 0.21789941  0.47417863 -1.15061414 -4.40515755]
[ 0.22738298  0.64682607 -1.23871729 -4.77922512]
[ 0.2403195   0.44805604 -1.3343018  -4.95996163]
[ 0.24928062  0.61178872 -1.43350103 -5.30332112]
[ 0.2615164   0.77029336 -1.53956745 -5.62709498]
[ 0.27692226  0.9237672  -1.65210935 -5.92813969]
[ 0.29539761  0.70892805 -1.77067215 -6.24734325]
[ 0.30957617  0.48914384 -1.89561901 -6.60094652]
[ 0.31935905  0.63036086 -2.02763794 -6.81197033]
[ 0.33196626  0.40236903 -2.16387735 -7.22667688]
[ 0.34001364  0.17003966 -2.30841089 -7.66524811]
[ 0.34341444 -0.06521541 -2.46171585 -8.1201523 ]
[ 0.34211013  0.07830095 -2.62411889 -8.137581  ]
[ 0.34367615 -0.15084287 -2.78687051 -8.58173235]
[ 0.34065929 -0.37362499 -2.95850516 -8.99721589]
[ 0.33318679 -0.58518006 -3.13844948 -9.36277217]
[ 0.32148319 -0.78061576 -3.32570492 -9.65684837]
[ 0.30587087 -0.56678094 -3.51884189 -9.2876934 ]
[ 0.29453526 -0.33801834 -3.70459576 -8.86037971]
[ 0.28777489 -0.482771   -3.88180335 -8.88708007]


[ 0.02563621  0.00518887 -0.03890211 -0.03420667]
[ 0.02573998  0.20084647 -0.03958624 -0.33890536]
[ 0.02975691  0.00630951 -0.04636435 -0.05896384]
[ 0.0298831  -0.18811806 -0.04754362  0.21873787]
[ 0.02612074 -0.38252928 -0.04316887  0.49605262]
[ 0.01847016 -0.57701675 -0.03324781  0.77482433]
[ 0.00692982 -0.38145361 -0.01775133  0.47186869]
[-0.00069925 -0.18608549 -0.00831395  0.17364406]
[-0.00442096  0.00915445 -0.00484107 -0.12165001]
[-0.00423787  0.20434543 -0.00727407 -0.41585631]
[-0.00015096  0.00932732 -0.0155912  -0.12547545]
[ 3.55836451e-05  2.04669123e-01 -1.81007082e-02 -4.23036165e-01]
[ 0.00412897  0.00980822 -0.02656143 -0.136114  ]
[ 0.00432513 -0.18492341 -0.02928371  0.14807227]
[ 0.00062666 -0.37961405 -0.02632227  0.43137483]
[-0.00696562 -0.18412946 -0.01769477  0.13051167]
[-0.01064821  0.01124144 -0.01508454 -0.16770079]
[-0.01042338  0.20657603 -0.01843855 -0.46510402]
[-0.00629186  0.01171941 -0.02774063 -0.1782894 ]
[-0.00605747 -0.18299481 -0.031306

[ 2.15111728  2.06822135 -5.85419324 -1.28854782]
[ 2.19248171  1.87084708 -5.8799642  -0.89702328]
[ 2.22989865  1.67308504 -5.89790467 -0.50880979]
[ 2.26336035  1.47510933 -5.90808086 -0.12312488]
[ 2.29286254  1.27704909 -5.91054336  0.26102128]
[ 2.31840352  1.46550438 -5.90532293  0.10477798]
[ 2.34771361  1.26744118 -5.90322737  0.48938109]
[ 2.37306243  1.4558142  -5.89343975  0.33601276]
[ 2.40217872  1.64395025 -5.8867195   0.18667857]
[ 2.43505772  1.83192576 -5.88298593  0.04011802]
[ 2.47169624  1.63385831 -5.88218356  0.42828623]
[ 2.5043734   1.82180082 -5.87361784  0.28349675]
[ 2.54080942  2.00953709 -5.86794791  0.14225747]
[ 2.58100016e+00  2.19713931e+00 -5.86510276e+00  3.36934226e-03]
[ 2.62494295  1.99908499 -5.86503537  0.39422955]
[ 2.66492465  2.18668319 -5.85715078  0.25646168]
[ 2.70865831  2.37409267 -5.85202154  0.12197511]
[ 2.75614016  2.56138191 -5.84958204 -0.01037675]
[ 2.8073678   2.36334995 -5.84978958  0.38270385]
[ 2.8546348   2.55064897 -5.842135

In [1]:
def data_preparation(N, K, f, render=False):
  game_data = []
  for i in range(N):
    score = 0
    game_steps = []
    obs = env.reset()
    for step in range(goal_steps):
      if render: env.render()
      action = f(obs)
      game_steps.append((obs, action))
      obs, reward, done, info = env.step(action)
      score += reward
      if done:
        break
    game_data.append((score, game_steps))
  
  game_data.sort(key=lambda s:-s[0])
  
  training_set = []
  for i in range(K):
    for step in game_data[i][1]:
      if step[1] == 0:
        training_set.append((step[0], [1, 0]))
      else:
        training_set.append((step[0], [0, 1]))

  print("{0}/{1}th score: {2}".format(K, N, game_data[K-1][0]))
  if render:
    for i in game_data:
      print("Score: {0}".format(i[0]))
  
  return training_set

In [2]:
from keras.models     import Sequential
from keras.layers     import Dense
from keras.optimizers import Adam  
def build_model():
  model = Sequential()
  model.add(Dense(128, input_dim=4, activation='relu'))
  model.add(Dense(52, activation='relu'))
  model.add(Dense(2, activation='softmax'))
  model.compile(loss='mse', optimizer=Adam())
  return model

Using TensorFlow backend.


In [3]:
def train_model(model, training_set):
  X = np.array([i[0] for i in training_set]).reshape(-1, 4)
  y = np.array([i[1] for i in training_set]).reshape(-1, 2)
  model.fit(X, y, epochs=10)

In [6]:
import gym
import numpy as np
import random

env = gym.make('CartPole-v1')
goal_steps = 500

training_data = data_preparation(1000, 50, lambda s: random.randrange(0, 2))

50/1000th score: 47.0


In [7]:
if __name__ == '__main__':
  N = 1000
  K = 50
  model = build_model()
  training_data = data_preparation(N, K, lambda s: random.randrange(0, 2))
  train_model(model, training_data)
  
  def predictor(s):
    return np.random.choice([0, 1], p=model.predict(s.reshape(-1, 4))[0] )
    
  data_preparation(100, 100, predictor, True)

W0915 09:40:04.102341  9912 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



50/1000th score: 47.0


W0915 09:40:04.265410  9912 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/10
2960/2960 [==============================] - 2s 696us/step - loss: 0.2432
Epoch 2/10
2960/2960 [==============================] - 0s 88us/step - loss: 0.2409
Epoch 3/10
2960/2960 [==============================] - 0s 90us/step - loss: 0.2384
Epoch 4/10
2960/2960 [==============================] - 0s 86us/step - loss: 0.2384
Epoch 5/10
2960/2960 [==============================] - 0s 86us/step - loss: 0.2373
Epoch 6/10
2960/2960 [==============================] - 0s 85us/step - loss: 0.2366
Epoch 7/10
2960/2960 [==============================] - 0s 85us/step - loss: 0.2363
Epoch 8/10
2960/2960 [==============================] - 0s 85us/step - loss: 0.2361
Epoch 9/10
2960/2960 [==============================] - 0s 104us/step - loss: 0.2355
Epoch 10/10
2960/2960 [==============================] - 0s 131us/step - loss: 0.2345
100/100th score: 10.0
Score: 128.0
Score: 123.0
Score: 119.0
Score: 114.0
Score: 108.0
Score: 106.0
Score: 100.0
Score: 100.0
Score: 99.0
Score: 98.0
Score: