# PyTorch Tensor Basic Usage
- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

In [1]:
import torch
torch.__version__

'1.4.0'

### 1. Create Tensor
#### 1) random numbers

In [2]:
x = torch.rand(2,3)  # [0, 1)
x

tensor([[0.6796, 0.2241, 0.4527],
        [0.4051, 0.5279, 0.8319]])

In [3]:
x = torch.randn(2, 3)  # Z(0, 1)
x

tensor([[-1.0962, -0.8291, -0.2644],
        [ 0.0405, -1.2532, -1.9161]])

In [4]:
x = torch.randperm(5)  # permutation
x

tensor([3, 2, 1, 0, 4])

#### 2) zeros, ones, arange

In [5]:
torch.zeros(2, 3) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2, 3) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
x = torch.rand(2,3)
torch.zeros_like(x), torch.ones_like(x)  # x와 동일한 shape, device

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [8]:
torch.arange(0, 10, step=2) 

tensor([0, 2, 4, 6, 8])

#### 3) Tensor DataType

In [9]:
x = torch.FloatTensor(2, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [10]:
torch.FloatTensor([2,3]) 

tensor([2., 3.])

In [11]:
x = x.type_as(torch.IntTensor())
x

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

#### 4) Numpy to Tensor, Tensor to Numpy

In [12]:
import numpy as np
x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [13]:
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

#### 5) Tensor on CPU & GPU

In [14]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [16]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### 6) Tensor Size

In [17]:
x = torch.FloatTensor(10, 12, 3, 4)
x.size() 

torch.Size([10, 12, 3, 4])

#### 7) View(Reshape)

In [18]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape) 

torch.Size([2, 2, 3])


In [19]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [20]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 2. Indexing, Slicing, Joining
#### 1) Indexing

In [21]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x, 0, torch.LongTensor([0,3]))
x, out

(tensor([[0.3898, 0.9988, 0.8990],
         [0.2823, 0.7577, 0.6538],
         [0.1125, 0.3469, 0.2372],
         [0.7073, 0.5921, 0.5928]]),
 tensor([[0.3898, 0.9988, 0.8990],
         [0.7073, 0.5921, 0.5928]]))

In [22]:
# python-style indexing

x[:,0], x[0,:], x[0:2,0:2] 

(tensor([0.3898, 0.2823, 0.1125, 0.7073]),
 tensor([0.3898, 0.9988, 0.8990]),
 tensor([[0.3898, 0.9988],
         [0.2823, 0.7577]]))

In [23]:
# torch.maseked_select(input, mask)

x = torch.rand(2, 3)
mask = torch.BoolTensor([[0,0,1], [0,1,0]])
out = torch.masked_select(x, mask)
x, mask, out

(tensor([[0.3695, 0.4653, 0.2979],
         [0.0298, 0.6133, 0.3130]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([0.2979, 0.6133]))

#### 2) Joining

In [24]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z0 = torch.cat([x1, x2], dim=0)
z1 = torch.cat([x1, x2], dim=1)
x1, x2, z0, z1

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [25]:
# torch.stack(sequence, dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack0 = torch.stack([x,x,x], dim=0)
x_stack1 = torch.stack([x,x,x], dim=1)
x_stack0, x_stack1

(tensor([[[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]]]),
 tensor([[[1., 2., 3.],
          [1., 2., 3.],
          [1., 2., 3.]],
 
         [[4., 5., 6.],
          [4., 5., 6.],
          [4., 5., 6.]]]))

#### 3) Slicing

In [26]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x1, x2 = torch.chunk(z0, 2, dim=0)
y1, y2, y3 = torch.chunk(z0, 3, dim=1)
z0, x1, x2, y1, y2, y3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [27]:
# torch.split(tensor, split_size, dim=0) -> split into specific size

x1, x2 = torch.split(z0, 2, dim=0)
y1, y2 = torch.split(z0, 2, dim=1)
z0, x1, x2, y1, y2

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.],
         [ 4.,  5.],
         [-1., -2.],
         [-4., -5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

#### 4) Squeezing

In [28]:
# torch.squeeze(input, dim=None) -> reduce dim by 1

x = torch.FloatTensor(10, 1, 3, 1, 4)
y = torch.squeeze(x)
x.size(), y.size() 

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [29]:
# torch.unsqueeze(input, dim=None) -> add dim by 1

x = torch.FloatTensor(10, 3, 4)
y0 = torch.unsqueeze(x, dim=0)
y1 = torch.unsqueeze(x, dim=1)
y2 = torch.unsqueeze(x, dim=2)

x.size(), y0.size(), y1.size(), y2.size(), x.unsqueeze(-1).shape

(torch.Size([10, 3, 4]),
 torch.Size([1, 10, 3, 4]),
 torch.Size([10, 1, 3, 4]),
 torch.Size([10, 3, 1, 4]),
 torch.Size([10, 3, 4, 1]))

#### 5) In-place operation

In [30]:
x = torch.FloatTensor([[1,2], [3,4]])

print(x.mul(2.))  # x는 변하지 않음
print(x)
print(x.mul_(2.))  # in-place op, x가 변함
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### 3. Initialization

In [31]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4), a=0, b=9)
x2 = init.normal_(torch.FloatTensor(3,4), std=3.2)
x3 = init.constant_(torch.FloatTensor(3,4), 3.14159)
x1, x2, x3

(tensor([[5.3578, 1.4494, 2.1415, 2.7719],
         [5.4588, 5.2341, 0.6552, 3.5455],
         [3.9724, 8.4766, 6.0646, 3.8249]]),
 tensor([[-4.1581, -1.2833,  0.0151,  1.5129],
         [ 0.3685,  8.0304, -7.0209,  5.5496],
         [ 2.7974,  2.0701, -7.9857, -2.3490]]),
 tensor([[3.1416, 3.1416, 3.1416, 3.1416],
         [3.1416, 3.1416, 3.1416, 3.1416],
         [3.1416, 3.1416, 3.1416, 3.1416]]))

### 4. Math Operations
#### 1) Arithmetic operations

In [32]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
torch.add(x1,x2), x1+x2, x1-x2

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]))

In [33]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1, 10)
x2, x1+10

(tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]))

In [34]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
torch.mul(x1,x2), x1*x2

(tensor([[ -1.,  -4.,  -9.],
         [-16., -25., -36.]]),
 tensor([[ -1.,  -4.,  -9.],
         [-16., -25., -36.]]))

In [35]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
torch.div(x1,x2), x1/x2

(tensor([[-1., -1., -1.],
         [-1., -1., -1.]]),
 tensor([[-1., -1., -1.],
         [-1., -1., -1.]]))

#### 2) Other math operations

In [36]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
torch.pow(x,2), x**2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [37]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
torch.exp(x) 

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [38]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
torch.log(x) 

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

#### 3) Matrix operations

In [39]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.transpose(x1, 0, 1)
x1, x2, torch.mm(x1, x2) 

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]),
 tensor([[14., 32.],
         [32., 77.]]))

In [40]:
# batch matrix multiplication

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
torch.bmm(x1, x2).size() 

torch.Size([10, 3, 5])

In [41]:
# dot product (1차원만 가능) 
x1 = torch.FloatTensor([1,2,3])
x2 = torch.FloatTensor([-1,-2,-3])
torch.dot(x1,x2) 

tensor(-14.)

In [42]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x1.t(), torch.transpose(x1, 0, 1) 

(tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]),
 tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]))

In [43]:
x1 = torch.FloatTensor(10,3,4)

x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size() 

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [44]:
# eigen value and eigen vector
x = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
x, torch.eig(x, True) 

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.return_types.eig(
 eigenvalues=tensor([[ 1.6117e+01,  0.0000e+00],
         [-1.1168e+00,  0.0000e+00],
         [ 2.9486e-07,  0.0000e+00]]),
 eigenvectors=tensor([[-0.2320, -0.7858,  0.4082],
         [-0.5253, -0.0868, -0.8165],
         [-0.8187,  0.6123,  0.4082]])))

In [45]:
torch.mm(x, torch.eig(x,True)[1]) 

tensor([[-3.7386e+00,  8.7765e-01,  2.9802e-08],
        [-8.4665e+00,  9.6888e-02, -6.5565e-07],
        [-1.3194e+01, -6.8387e-01, -7.4506e-07]])