# Scipy 행렬 다루기

In [1]:
import numpy as np

b1 = -1 * np.ones((4,), dtype=np.float64)
b2 = 2 * np.ones((5,), dtype=np.float64)
b3 = np.ones((4,), dtype=np.float64) 

In [2]:
A = np.diag(b1, k=-1) + np.diag(b2) + np.diag(b3, k=1)
A

array([[ 2.,  1.,  0.,  0.,  0.],
       [-1.,  2.,  1.,  0.,  0.],
       [ 0., -1.,  2.,  1.,  0.],
       [ 0.,  0., -1.,  2.,  1.],
       [ 0.,  0.,  0., -1.,  2.]])

## Matrix multiplication

In [3]:
P = np.array([[1,2], [3,4]])
Q = np.array([[5,6], [7,8]])
R = P @ Q
R

array([[19, 22],
       [43, 50]])

In [6]:
Q @ P

array([[23, 34],
       [31, 46]])

In [4]:
P * Q

array([[ 5, 12],
       [21, 32]])

In [5]:
Q * P

array([[ 5, 12],
       [21, 32]])

In [8]:
r = np.array([2, 4]).reshape(-1, 1)
r

array([[2],
       [4]])

In [9]:
P * r

array([[ 2,  4],
       [12, 16]])

In [10]:
P @ r

array([[10],
       [22]])

## Toeplitz 행렬

In [11]:
import scipy.linalg as lin

c = np.array([1,3,6,10], dtype=np.float64)
r = np.array([1,-1,-2,-3], dtype=np.float64)
b = np.ones((4,), dtype=np.float64) 

In [12]:
x = lin.solve_toeplitz((c, r), b)
x

array([ 1.66666667e-01, -5.27355937e-16, -1.66666667e-01, -1.66666667e-01])

In [13]:
t_full = lin.toeplitz(c, r)
t_full

array([[ 1., -1., -2., -3.],
       [ 3.,  1., -1., -2.],
       [ 6.,  3.,  1., -1.],
       [10.,  6.,  3.,  1.]])