In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    boston.data, boston.target, test_size=0.2, random_state=2022
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404,), (102,))

In [15]:
from sklearn.linear_model import Ridge, Lasso, LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.6225687597000794

In [16]:
for alpha in [1, 10, 100]:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train, y_train)
    score = ridge.score(X_test, y_test)
    print(alpha, score)

1 0.6120292876368372
10 0.6081472488371757
100 0.6352332164732378


In [17]:
for alpha in [1, 10, 100]:
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_train, y_train)
    score = lasso.score(X_test, y_test)
    print(alpha, score)

1 0.6471885919727083
10 0.5944934950244617
100 0.25457490005059613


In [18]:
from sklearn.preprocessing import StandardScaler
scaled_data = StandardScaler().fit_transform(boston.data)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    scaled_data, boston.target, test_size=0.2, random_state=2022
)

In [20]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.6225687597000791

In [28]:
for alpha in [0.1, 1, 10, 100]:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train, y_train)
    score = ridge.score(X_test, y_test)
    print(alpha, score)

0.1 0.6225985056536674
1 0.6228572277518352
10 0.6249828938200858
100 0.641338157851348


In [29]:
for alpha in [0.1, 1, 10, 100]:
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_train, y_train)
    score = lasso.score(X_test, y_test)
    print(alpha, score)

0.1 0.6192407247468066
1 0.5917669598811085
10 -0.09366578724692776
100 -0.09366578724692776


In [23]:
ridge.coef_, ridge.intercept_

(array([-0.67929406,  0.50223653, -0.29760183,  0.7439901 , -0.68925021,
         3.17053808, -0.29536822, -1.54153261,  0.58135392, -0.55826092,
        -1.59110132,  0.79365281, -2.8316445 ]),
 22.552736704621044)

In [24]:
lr.coef_, lr.intercept_

(array([-0.93972232,  0.9729935 ,  0.33738473,  0.69902083, -1.59087926,
         3.3077585 , -0.33648694, -3.01917884,  2.59805965, -2.08168423,
        -1.93687879,  0.94392486, -3.7178099 ]),
 22.533430413143368)

In [25]:
lasso.coef_, lasso.intercept_

(array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.]),
 23.054455445544555)

In [26]:
lasso = Lasso(1)
lasso.fit(X_train, y_train)
lasso.score(X_test, y_test)

0.5917669598811085

In [27]:
lasso.coef_, lasso.intercept_

(array([-0.        ,  0.        , -0.        ,  0.0316145 , -0.        ,
         3.33398568, -0.        , -0.        , -0.        , -0.        ,
        -1.31377601,  0.24439636, -3.33494748]),
 22.554708575390944)