# 원, 삼각형, 사각형 구분하기
## Local에서 작업
## 2. 어려운 테스트 문제를 기존 CNN 모델로 푸는 경우

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

# 랜덤시드 고정시키기
np.random.seed(3)

Using TensorFlow backend.


### 데이터셋 생성하기

In [2]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'hard_handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'hard_handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


### 모델 구성하기

In [4]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu', input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
________________________________________________

### 모델 학습과정 설정하기

In [6]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## 모델 학습시키기
- 첫번째 인자 : 훈련데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 train_generator으로 지정.
- steps_per_epoch : 한 epoch에 사용한 스텝 수를 지정. 총 45개의 훈련 샘플이 있고 배치사이즈가 3이므로 15 스텝으로 지정.
- epochs : 전체 훈련 데이터셋에 대해 학습 반복 횟수를 지정. 200번을 반복적으로 학습.
- validation_data : 검증데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 validation_generator으로 지정.
- validation_steps : 한 epoch 종료 시 마다 검증할 때 사용되는 검증 스텝 수를 지정. 홍 15개의 검증 샘플이 있고 배치사이즈가 3이므로 5 스텝으로 지정.

In [7]:
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

W0904 15:54:34.127145 13240 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0904 15:54:34.185176 13240 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/200
15/15 [==============================] - 3s 202ms/step - loss: 1.0455 - acc: 0.5778 - val_loss: 1.6502 - val_acc: 0.3333
Epoch 2/200
15/15 [==============================] - 0s 9ms/step - loss: 0.3071 - acc: 0.8889 - val_loss: 1.9359 - val_acc: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 10ms/step - loss: 0.0396 - acc: 1.0000 - val_loss: 3.1860 - val_acc: 0.3333
Epoch 4/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0048 - acc: 1.0000 - val_loss: 3.9082 - val_acc: 0.3333
Epoch 5/200
15/15 [==============================] - 0s 9ms/step - loss: 7.9161e-04 - acc: 1.0000 - val_loss: 4.2593 - val_acc: 0.3333
Epoch 6/200
15/15 [==============================] - 0s 9ms/step - loss: 4.5133e-04 - acc: 1.0000 - val_loss: 4.4351 - val_acc: 0.3333
Epoch 7/200
15/15 [==============================] - 0s 9ms/step - loss: 3.4566e-04 - acc: 1.0000 - val_loss: 4.5037 - val_acc: 0.3333
Epoch 8/200
15/15 [==============================] - 0s 10ms/step - 

15/15 [==============================] - 0s 9ms/step - loss: 6.8983e-06 - acc: 1.0000 - val_loss: 5.8408 - val_acc: 0.3333
Epoch 62/200
15/15 [==============================] - 0s 9ms/step - loss: 6.5301e-06 - acc: 1.0000 - val_loss: 5.8506 - val_acc: 0.3333
Epoch 63/200
15/15 [==============================] - 0s 9ms/step - loss: 6.1632e-06 - acc: 1.0000 - val_loss: 5.8665 - val_acc: 0.3333
Epoch 64/200
15/15 [==============================] - 0s 9ms/step - loss: 5.8572e-06 - acc: 1.0000 - val_loss: 5.8779 - val_acc: 0.3333
Epoch 65/200
15/15 [==============================] - 0s 9ms/step - loss: 5.4837e-06 - acc: 1.0000 - val_loss: 5.8871 - val_acc: 0.3333
Epoch 66/200
15/15 [==============================] - 0s 10ms/step - loss: 5.2333e-06 - acc: 1.0000 - val_loss: 5.9038 - val_acc: 0.3333
Epoch 67/200
15/15 [==============================] - 0s 10ms/step - loss: 4.9750e-06 - acc: 1.0000 - val_loss: 5.9168 - val_acc: 0.3333
Epoch 68/200
15/15 [==============================] - 0s 9m

15/15 [==============================] - 0s 9ms/step - loss: 4.4505e-07 - acc: 1.0000 - val_loss: 6.3272 - val_acc: 0.3333
Epoch 122/200
15/15 [==============================] - 0s 9ms/step - loss: 4.3843e-07 - acc: 1.0000 - val_loss: 6.3306 - val_acc: 0.3333
Epoch 123/200
15/15 [==============================] - 0s 9ms/step - loss: 4.2121e-07 - acc: 1.0000 - val_loss: 6.3371 - val_acc: 0.3333
Epoch 124/200
15/15 [==============================] - 0s 9ms/step - loss: 4.1326e-07 - acc: 1.0000 - val_loss: 6.3423 - val_acc: 0.3333
Epoch 125/200
15/15 [==============================] - 0s 9ms/step - loss: 4.0531e-07 - acc: 1.0000 - val_loss: 6.3487 - val_acc: 0.3333
Epoch 126/200
15/15 [==============================] - 0s 9ms/step - loss: 3.9604e-07 - acc: 1.0000 - val_loss: 6.3525 - val_acc: 0.3333
Epoch 127/200
15/15 [==============================] - 0s 10ms/step - loss: 3.8677e-07 - acc: 1.0000 - val_loss: 6.3566 - val_acc: 0.3333
Epoch 128/200
15/15 [==============================] -

15/15 [==============================] - 0s 10ms/step - loss: 1.8279e-07 - acc: 1.0000 - val_loss: 6.5460 - val_acc: 0.3333
Epoch 181/200
15/15 [==============================] - 0s 9ms/step - loss: 1.8279e-07 - acc: 1.0000 - val_loss: 6.5480 - val_acc: 0.3333
Epoch 182/200
15/15 [==============================] - 0s 10ms/step - loss: 1.8146e-07 - acc: 1.0000 - val_loss: 6.5510 - val_acc: 0.3333
Epoch 183/200
15/15 [==============================] - 0s 9ms/step - loss: 1.8014e-07 - acc: 1.0000 - val_loss: 6.5555 - val_acc: 0.3333
Epoch 184/200
15/15 [==============================] - 0s 10ms/step - loss: 1.8014e-07 - acc: 1.0000 - val_loss: 6.5575 - val_acc: 0.2667
Epoch 185/200
15/15 [==============================] - 0s 10ms/step - loss: 1.7881e-07 - acc: 1.0000 - val_loss: 6.5610 - val_acc: 0.2667
Epoch 186/200
15/15 [==============================] - 0s 10ms/step - loss: 1.7881e-07 - acc: 1.0000 - val_loss: 6.5627 - val_acc: 0.2667
Epoch 187/200
15/15 [=============================

### 모델 평가하기

In [8]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 26.67%


### 모델 사용하기

In [9]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 0.000 1.000]
 [0.001 0.000 0.999]
 [0.515 0.000 0.485]
 [0.143 0.000 0.857]
 [0.000 0.000 1.000]
 [0.105 0.001 0.894]
 [0.000 0.002 0.998]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.007 0.993]
 [0.004 0.000 0.996]
 [0.000 0.000 1.000]
 [0.932 0.001 0.067]
 [0.000 0.000 1.000]
 [0.000 0.005 0.995]]
