# Variable & Automatic Gradient Calculation
- Tensor vs Variable
- Grapt and Gradient

### 1. Import required libraries

In [1]:
import torch
from torch.autograd import Variable

### 2. Tensor vs Variable
#### 1) Declaration

In [2]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
x_variable = Variable(x_tensor)
x_variable

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### 2) Variables of a variable

In [4]:
x_variable.data

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
print(x_variable.grad) 

None


In [8]:
print(x_variable.requires_grad)

x_var = Variable(x_tensor, requires_grad=True)
x_var.requires_grad

False


True

### 3. Graphs & Variables

In [10]:
x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [11]:
loss = torch.FloatTensor(3,4)
z.backward(loss)
print(x.grad)
y.grad, z.grad

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


(None, None)